name: Build packages
on:
  pull_request:
  push:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:
jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      INSPIRCD_VERSION: ${{ steps.version.outputs.INSPIRCD_VERSION }}
    steps:
      - name: Retrieve latest release
        id: version
        run: |
          INSPIRCD_VERSION=$(curl https://api.github.com/repos/inspircd/inspircd/releases | jq --raw-output 'map(select((.draft or .prerelease | not) and (.tag_name | startswith("v4.")))) | first .tag_name | .[1:]')
          if [ -z "${INSPIRCD_VERSION}" ]
          then
            exit 1
          fi
          echo "Building packages for InspIRCd ${INSPIRCD_VERSION}"
          echo "INSPIRCD_VERSION=${INSPIRCD_VERSION}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    env:
      INSPIRCD_RPM_PLATFORMS: ${{ matrix.package == 'rpm' && matrix.platform || null }}
      INSPIRCD_IGNORE_WARNINGS: 1
      INSPIRCD_VERSION: ${{ needs.version.outputs.INSPIRCD_VERSION }}
      INSPIRCD_PACKAGES: ${{ matrix.package }} html
      INSPIRCD_REVISION: ${{ github.sha }}
    needs:
      - version
    steps:
      - uses: actions/checkout@v6

      - name: Build packages
        run: ./build.sh

      - name: List packages
        run: cat ./build/packages.yml

      - name: Upload packages
        uses: actions/upload-artifact@v6
        with:
          name: inspircd-${{ matrix.platform }}
          path: |
            ./build/*.deb
            ./build/*.ddeb

    strategy:
      fail-fast: false
      matrix:
        include:
          - package: deb
            platform: Debian